spring:
  data:
    cassandra:
      keyspace-name: simplechatapp
      username: <username>
      password: <secret>
      schema-action: create_if_not_exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

datastax.astra:
    secure-connect-bundle: secure-connect-simplechatapplication.zip

astra.db:
    id: <db-id>
    region: us-east1
    keyspace: simplechatapp
    application.token: <token>
